version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:
      - mv target/deploy ./
      - echo Build completed
artifacts:
  files:
      - deploy/'**/*'
